#!/usr/bin/env python

import argparse
import time

from chroma import engine


if __name__ == '__main__':
	tkgui = None

	parser = argparse.ArgumentParser()
	parser.add_argument('input', help="path to MIDI file, or 'usbmidi' for real-time USB-MIDI")
	parser.add_argument('output', nargs=argparse.REMAINDER, choices=('arduino', 'tkinter', 'usbmidi'))
	args = parser.parse_args()

	if args.input == 'usbmidi':
		from chroma import midiserial
		midiserial.MidiInput().start()
	else:
		from chroma import smfreader
		smfreader.SMFReader(args.input).start()

	for output in set(args.output):
		if output == 'arduino':
			from chroma import usbserial
			engine.listeners.append(usbserial.get_output())
		elif output == 'tkinter':
			from chroma import tkgui
			engine.listeners.append(tkgui.TkListener())
		elif output == 'usbmidi':
			from chroma import midiserial
			engine.handlers.append(midiserial.MidiOutput())
		else:
			print "Unknown output", output

	engine.start_queue_proc()
	if tkgui:
		tkgui.run()
	else:
		while True:
			time.sleep(1)

